### ISSUE TITLE
get pos and rot of image extractor

### ISSUE THREAD

**Issue by derrick-xwp** [facebookresearch/habitat-sim#1793] opened 2022-06-28 13:48 UTC
poses = self.mode_to_data[mymode]
pos, rot, fp = poses[idx]

if fp != self.cur_fp:
    self.sim.reconfigure(self._config_sim(fp, self.img_size))
    self.cur_fp = fp

new_state = AgentState()
new_state.position = pos
new_state.rotation = rot

Hi, is above code a correct way to get the extrinsic params of rendered images?
What is the coordinate system of habitat-sim?

**Comment by aclegg3** [comment] 2022-07-05 20:22
Duplicate of #1282. Yes, use the agent. 

If the sensor is offset from the agent (default 1.5m +Y), then you may want to acquire the sensor SceneNode directly and use the [absolute_transformation](https://aihabitat.org/docs/habitat-sim/habitat_sim.scene.SceneNode.html#absolute_transformation) instead.

Regarding coordinate system:

> In habitat the camera faces along -Z, +Y is up, and +X is right. This is what OpenGL uses.

**Closed by aclegg3** 2022-07-05 20:22 UTC
