### ISSUE TITLE
Does the latest version of habitat sim support EquirectangularDepthSensor?

### ISSUE THREAD

**Issue by zhai-create** [facebookresearch/habitat-sim#2273] opened 2023-11-28 07:11 UTC
## Habitat-Sim version
v0.3.0

I want to use EquirectangularDepthSensor data in the experiment, but it seems that I cannot successfully complete the configuration. May I ask if the latest version of habitat sim supports EquirectangularDepthSensor?

**Comment by zhai-create** [comment] 2023-11-28 07:16
EquirectangularDepthSensor seems to be supported on previous versions (such as v0.2.0) of habitat lab and habitat sim.

**Comment by aclegg3** [comment] 2023-11-28 16:49
Duplicate of [lab issue](https://github.com/facebookresearch/habitat-lab/issues/1701?fbclid=IwAR0yF-3MuCZy1DbfXP_ILZDoDre3Lopz5FqNnF-9IpdkJYkvoiR70Um3tv8).

**Closed by aclegg3** 2023-11-28 16:49 UTC
