### ISSUE TITLE
Rigid Body tutorial example throws error

### ISSUE THREAD

**Issue by abhishek-tcs-rni** [facebookresearch/habitat-sim#951] opened 2020-11-30 16:14 UTC
## ❓ Questions and Help

I have installed `habitat-sim` as per given [instructions](https://github.com/facebookresearch/habitat-sim#installation), and also successfully performed [testing](https://github.com/facebookresearch/habitat-sim#testing), including extraction of pre-processed object dataset to `habitat-sim/data/objects/`.

Corresponding to [Interactive Rigid Objects](https://aihabitat.org/docs/habitat-sim/rigid-object-tutorial.html) tutorial, on running given example script in installed `conda` environment in `habitat-sim` directory
```
python examples/tutorials/nb_python/rigid_object_tutorial.py
```
the following error is displayed
```
Simulating 1.5 world seconds.
Encoding the video: examples/tutorials/rigid_object_tutorial_output/sim_basics.mp4 
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
Traceback (most recent call last):
  File "examples/tutorials/nb_python/rigid_object_tutorial.py", line 196, in <module>
    )[0]
IndexError: list index out of range
```

It appears the [statement](https://github.com/facebookresearch/habitat-sim/blob/0aea76a27eb70ba5cf80be9b847557f5857f09de/examples/tutorials/nb_python/rigid_object_tutorial.py#L193) loading the template for object, `cheezit` using the instruction, [`obj_templates_mgr.get_template_handles`](https://aihabitat.org/docs/habitat-sim/habitat_sim.attributes_managers.StageAttributesManager.html#get_template_handles) is throwing the above error.

Please help in resolving above error, to run the complete [example script](https://github.com/facebookresearch/habitat-sim/blob/master/examples/tutorials/nb_python/rigid_object_tutorial.py) corresponding to [Rigid Body tutorial](https://aihabitat.org/docs/habitat-sim/rigid-object-tutorial.html) without errors.

**Comment by aclegg3** [comment] 2020-11-30 18:32
Hey @abhishek-tcs-rni, 

This tutorial is working on my system and [the Collab](https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/master/examples/tutorials/colabs/rigid_object_tutorial.ipynb) for current master branch. 

Looks like you may not have a properly configured data folder if the object cannot be found. You should have the object assets and configs in the `data/objects/` directory like so:
![image](https://user-images.githubusercontent.com/1445143/100649298-183e9e80-32f7-11eb-99be-990f0783bac7.png)

Is this the case?

**Comment by abhishek-tcs-rni** [comment] 2020-12-01 05:52
Hey @aclegg3,

The data sub-folder does contain the same contents. As instructed, I had extracted to `habitat-sim/data/objects/` directory from [here](http://dl.fbaipublicfiles.com/habitat/objects_v0.2.zip). A screenshot of contents of directories given below:
`habitat-sim/data/objects/`
![Screenshot from 2020-12-01 11-06-36](https://user-images.githubusercontent.com/74524523/100702088-fd3b5f80-33c6-11eb-9e66-fa7286445183.png) 
`habitat-sim`
![Screenshot from 2020-12-01 11-08-31](https://user-images.githubusercontent.com/74524523/100702101-07f5f480-33c7-11eb-830e-f1bdf2e771de.png)

Is anything missing here ?

**Comment by aclegg3** [comment] 2020-12-01 19:46
Hm, that looks fine. I'll need to see more log details before the error to know what is happening here. Likely that some path configuration is resulting in the object configs not being loaded into the ObjectAttributesManager properly.

**Comment by abhishek-tcs-rni** [comment] 2020-12-14 17:22
@aclegg3 I have attached the output on running the command below
```
python examples/tutorials/nb_python/rigid_object_tutorial.py
```
[rigid_object_tutorial.log](https://github.com/facebookresearch/habitat-sim/files/5690450/rigid_object_tutorial.log)

Please let me know if any other logs are required

**Comment by wouterreijgers** [comment] 2020-12-17 13:38
I am experiencing the same problem, after debugging I noticed that the command on line 159:
 `obj_templates_mgr = sim.get_object_template_manager()`
 returns nothing and that  the `obj_templates_mgr` is empty. 
 I was not yet able to find a solution yet.

**Comment by aclegg3** [comment] 2020-12-17 20:23
Thanks for the logs and details. @jturner65 any thoughts on this?

**Comment by jturner65** [comment] 2020-12-17 20:48
One thing i notice : this line "I1214 22:46:37.283061 16096 ObjectAttributesManager.cpp:294] Loading file-based object template: data/test_assets/objects/sphere.phys_properties.json"

This should instead attempt to load an ".object_config.json" file.  Something may have the inappropriate extension hardcoded.

**Comment by wouterreijgers** [comment] 2020-12-18 09:41
One thing I already discovered is that the code in the [tutorial about rigid objects](https://aihabitat.org/docs/habitat-sim/rigid-object-tutorial.html#simulation-quickstart) and the code that gets installed by default are slightly different. In the code that is already in the folder `examples/tutorials/nb_python/rigid_object_tutorial.py ` the command `obj_templates_mgr.load_configs(str(os.path.join(data_path, "objects")))` is missing, i believe this command is supposed to load the objects that are in the `data/objects` folder?

Although after adding this line the problem was not solved... 

@jturner65  the sphere actually works, the problem occurs when trying to load other objects. I think the problem is located in the following lines:

```
# [dynamic_control]
observations = []
obj_templates_mgr.load_configs(str(os.path.join(data_path, "objects")))
# search for an object template by key sub-string
cheezit_template_handle = obj_templates_mgr.get_template_handles("data/objects/cheezit")[0]
```
When executing these lines the log shows the following: 
```
Traceback (most recent call last):
  File "/home/wouter/PycharmProjects/habitat_sim_official_2/habitat-sim/examples/tutorials/nb_python/rigid_object_tutorial.py", line 194, in <module>
    obj_templates_mgr.load_configs(str(os.path.join(data_path, "objects")))
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.ObjectAttrib' object has no attribute 'load_configs'
```
After the debugging I found that the object `obj_templates_mgr` seems to be empty. It is created with the following command: `obj_templates_mgr = sim.get_object_template_manager()` but after looking in the `simulator.py` file I noticed that the function `get_object_template_manager` is not there although it is mentioned in [the documentation about the simulator](https://aihabitat.org/docs/habitat-sim/habitat_sim.simulator.Simulator.html#get_object_template_manager).

Also, when testing the simulator as mentioned [here](https://github.com/facebookresearch/habitat-sim#testing) (The thirth test). I noticed that although I loaded all the objects inside the correct folder I can not press the 'o', it keeps telling me that no objects are loaded.

**Comment by aclegg3** [comment] 2021-04-15 20:54
Closing as the updated issue (1014) was resolved.

**Closed by aclegg3** 2021-04-15 20:54 UTC
