### ISSUE TITLE
Using noise model for DepthSensor

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/habitat-sim#567] opened 2020-04-04 23:25 UTC
## ❓ Questions and Help
I was interested in getting the noisy depth inputs from Habitat-sim for training PointNav agents. For some reason, the depth outputs don't make any sense at all. For example, find some images below that were generated from the `test_sensors.py` script in habitat-api.  The left-hand side is the noisy RGB data with intensity 0.5 and the right-hand side is the noisy depth data with the Redwood depth model. It seemed more relevant to ask the question here because the noise models are primarily in habitat-sim.

![image](https://user-images.githubusercontent.com/31301440/78463337-39d08300-76a1-11ea-82cc-891694bbbe46.png)
![image](https://user-images.githubusercontent.com/31301440/78463365-6be1e500-76a1-11ea-96c7-1ae5aa31c902.png)
![image](https://user-images.githubusercontent.com/31301440/78463374-769c7a00-76a1-11ea-9b8a-7d9d3c3e1833.png)

**Comment by srama2512** [comment] 2020-04-05 00:47
I was using the stable version of habitat-sim. When I changed to the challenge-2020 tag, things started working well! May be this is worth keeping track of somewhere.

![image](https://user-images.githubusercontent.com/31301440/78464261-e6643200-76ac-11ea-8aaa-7757de7b296d.png) 
![image](https://user-images.githubusercontent.com/31301440/78464264-f1b75d80-76ac-11ea-9ecc-d86aaf265bf3.png)
![image](https://user-images.githubusercontent.com/31301440/78464266-fbd95c00-76ac-11ea-83b6-f40bb9346da1.png)

**Comment by erikwijmans** [comment] 2020-04-05 01:47
Hi, can you provide additional details?  What settings did compile on, what operating system, etc?

I tried to reproduce locally (on MacOS) by adding
```
cv2.imshow("Depth Noise", obs["depth"])
cv2.waitKey(0)
```
to the test you referenced in Habitat-API, but all looks fine.

**Comment by srama2512** [comment] 2020-04-05 06:38
Hi Erik,

Sure. This was compiled on an Ubuntu 18.04.3 LTS with the following:
- gcc 7.4.0
- cmake 3.10.2
- python 3.7
- cuda 10.1
# Testing
I installed habitat-sim as follows:
```
cd $HABITAT_ROOT
git clone --branch stable https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim
pip install -r requirements.txt
python setup.py install --headless --with-cuda
``` 

Habitat-api was a bit different. I had an older version that I made changes to for my project and then merged it with the master version (as of April 3rd, 2020).  In that merged habitat-api repository, I did the following:
```
cd $HABITAT_ROOT/habitat-api
ipython
>>> cd test
>>> from test_sensors import test_noise_models_rgbd
>>> cd ../
>>> test_noise_models_rgbd()
```
The `cd ...` steps were needed to bypass some path issues. I modified `test_noise_models_rgbd()` by setting `DEMO_MODE = True`. The screenshots I sent were from that video. Please let me know if there are any other details that I can add. 

# Fix
```
cd $HABITAT_ROOT
rm -rf habitat-sim
git  clone --branch challenge-2020 https://github.com/facebookresearch/habitat-sim.git
cd habitat-sim
pip install -r requirements.txt
python setup.py install --headless --with-cuda
```

**Comment by erikwijmans** [comment] 2020-04-05 17:16
Hmm, still can't reproduce.  Since this is fixed for you now, I will go ahead and close it.

**Closed by erikwijmans** 2020-04-05 17:16 UTC

**Comment by srama2512** [comment] 2020-04-06 02:37
Alright, thanks.
