### ISSUE TITLE
scene lighting doesn't work properly in lighting_tutorial.py

### ISSUE THREAD

**Issue by sparsh-umd** [facebookresearch/habitat-sim#1572] opened 2021-11-18 18:23 UTC
## Habitat-Sim version
0.2.1

## ❓ Questions and Help

I followed the instructions in https://aihabitat.org/docs/habitat-sim/lighting-setups.html#scene-lighting & ran the `lighting_tutorial.py` script. Object lighting works fine, but scene lighting doesn't. 

The 2nd & 3rd images the script generates should have been like https://aihabitat.org/docs/habitat-sim/1.jpg & https://aihabitat.org/docs/habitat-sim/2.jpg . But my 2nd & 3rd images are exactly similar to the 1st one(https://aihabitat.org/docs/habitat-sim/0.jpg). 

Thanks!

**Comment by aclegg3** [comment] 2021-11-18 19:14
Duplicate of #1450. We are aware the tutorial is out of date. Sorry about that! 😅  It's on the laundry list.

**Closed by aclegg3** 2021-11-18 19:14 UTC
